### ISSUE TITLE
Can not connect to Metamask wallet

### ISSUE THREAD

**Issue by JoelBeasley** [MorpheusAIs/Lite-Client#28]
Clicking on "Connect" does nothing
Clicking the the drop down "Select a network" > Any Option results in error "Error: Please connect to MetaMask"
<img width="1187" alt="Screenshot 2024-02-25 at 6 52 49 PM" src="https://github.com/MorpheusAIs/Node/assets/4238604/b89d0b13-6308-4a0a-b3d7-ffec89453415">

**Comment by JoelBeasley** [comment]
When you click "Connect" the first time it will show you a QR code. But if you close the QR code and try to click it again. Nothing happens. So you only have 1 chance to access the QR code.

Need to ensure that each time the button is clicked the QR code shows, not just the first time.

**Comment by betterbrand** [comment]
@dnovacik @IshShogun please diagnose and suggest fix

**Comment by dnovacik** [comment]
Yeah I've seen this happen, seems like it's actually a metamask error, but we might fix it on our side and terminate connection (thus forcing reset of the state)

More info: https://github.com/MetaMask/metamask-sdk/issues/651

**Comment by betterbrand** [comment]
Creating an issue to track

**Comment by betterbrand** [comment]
@dnovacik please determine the time to implement this fix.
