### ISSUE TITLE
Warning: ReactDOM.render is no longer supported 

### ISSUE THREAD

**Issue by JoelBeasley** [MorpheusAIs/Lite-Client#47]
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot

To reproduce: Boot project on Mac and check console.

**Comment by DavidAJohnston** [comment]
@betterbrand for your review. Don't know if its still the case for version 0.0.6 but FYI.

**Comment by betterbrand** [comment]
This seems to be concluded with https://github.com/MorpheusAIs/Lite-Client/pull/49. Please advise if error persists.
